FROM mysql:8.0.28

# Install applications needed
RUN apt update && apt upgrade -y
RUN apt-get install -y nano iputils-ping

#COPY ./custom.cnf /etc/mysql/conf.d/custom.cnf
#RUN chmod 0444 /etc/mysql/conf.d/custom.cnf
